# Generated by Django 5.2.10 on 2026-01-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('ventas', 'Ventas'), ('soporte', 'Soporte Técnico'), ('reclamo', 'Reclamo'), ('spam', 'Spam')], max_length=20, null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('neutral', 'Neutral'), ('negativo', 'Negativo')], max_length=20, null=True)),
                ('suggested_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
