# Generated by Django 5.2.10 on 2026-01-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='category',
            field=models.CharField(choices=[('sales', 'Sales'), ('support', 'Support'), ('complaint', 'Complaint'), ('spam', 'Spam')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='suggested_response',
            field=models.TextField(null=True),
        ),
    ]
